---
title: "Untitled"
author: "Solon Ioannou"
date: "7/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DatabaseConnector)
library(Eunomia)
library(SqlRender)
library(FeatureExtraction)
```

```{r}
connectionDetails <- getEunomiaConnectionDetails()
connection <- connect(connectionDetails)

cdmDatabaseSchema <- "main"
resultsDatabaseSchema <- "main"
```

```{r}
  sql <- SqlRender::readSql("src/createTable.sql")
  sql <- SqlRender::render(sql, target_database_schema = resultsDatabaseSchema, target_cohort_table = "new")
  sql <- SqlRender::translate(sql, targetDialect = connectionDetails$dbms)
  #connection <- DatabaseConnector::connect(connectionDetails)
 executeSql(connection, sql)
```


**Cohort:** Myocardial infarction

```{r}
sql <- readSql("data/cohorts/MI_2.sql")
sql <- render(sql,
              cdm_database_schema = "main",
              vocabulary_database_schema = "main", 
              target_database_schema = "main", 
              target_cohort_table = "cohort", 
              target_cohort_id = 1)

sql <- translate(sql, targetDialect = connectionDetails$dbms)
#connection <- connect(connectionDetails)
executeSql(connection, sql)
```

```{r}
querySql(connection, "SELECT * FROM CODESETS;")
querySql(connection, "SELECT COUNT(*) FROM CONDITION_OCCURRENCE WHERE CONDITION_CONCEPT_ID = 4329847")
```

```{r}
executeSql(connection, "DROP TABLE Codesets;
           DROP TABLE cohort_rows;
DROP TABLE final_cohort;
DROP TABLE inclusion_events;
DROP TABLE qualified_events;
DROP TABLE included_events;"
)
```


```{r}

disconnect(connection)
```

