---
title: "Untitled"
author: "Solon Ioannou"
date: "7/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(SqlRender)
library(DatabaseConnector)
```

```{r}
source("connections/connectionDetails_hds.R")

```

```{r}
connection <- connect(connectionDetails)
resultsDatabaseSchema = "scratch"
table = "new"
  sql <- SqlRender::readSql("src/createTable.sql")
  sql <- SqlRender::render(sql,
                           target_database_schema = resultsDatabaseSchema,
                           target_cohort_table = table)
  sql <- SqlRender::translate(sql, targetDialect = connectionDetails$dbms)
#  connection <- DatabaseConnector::connect(connectionDetails)
  DatabaseConnector::executeSql(connection, sql)
  #DatabaseConnector::disconnect(connection)

#}

#addTable(connectionDetails, "main", "new")
```


```{r}
#querySql(connection, "SELECT count(*) FROM person;")

cdmDatabaseSchema = "synpuf"
resultsDatabaseSchema = "sioannou"
targetDatabaseSchema = "sioannou"
targetCohortTable = "new"

sql <- readSql("data/cohorts/Heart_failure.sql")
#sql <- readSql("test.sql")
sql <- render(sql,
cdm_database_schema = cdmDatabaseSchema,
vocabulary_database_schema = "synpuf", 
target_database_schema = targetDatabaseSchema, 
target_cohort_table = targetCohortTable, 
target_cohort_id = 1)
sql <- translate(sql, targetDialect = connectionDetails$dbms)
#connection <- connect(connectionDetails)
executeSql(connection, sql)
```

```{r}
disconnect(connection)
```

