---
title: "Untitled"
author: "Solon Ioannou"
date: "7/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

search large spaces of possible patterns P and return
all patterns that satisfy user-defined constraints. 

However, a key limitation of frequent itemset mining is that the time dimension is ignored. To address this limitation, a more general problem called sequential pattern mining was proposed [3], [4], [5], which consists of identifying subsequences that appear frequently in a sequence database. A sequence is an ordered list of itemsets and can be used to represent various types of data such as protein sequences, text, click streams and event logs. Many studies have been devoted to SPM. The first SPM algorithms are AprioriAll and GSP [4], [5]. These latter apply a breadth-first search to count the support of sequences in a database and output all frequent sequences. Recently, more efficient sequential pattern mining algorithms were designed such as SPADE [6], FreeSpan [7], PrefixSpan [8], CM-SPADE [9], VMSP [10] and FCloSM
