---
title: "Untitled"
author: "Solon Ioannou"
date: "10/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rJava)
#.jinit()
.jclassPath()
#.jaddClassPath("/Users/solonioannou/IdeaProjects/SPMF_Algorithms/out/artifacts/SPMF_Algorithms_jar/SPMF_Algorithms.jar")
.jclassPath()
```

```{r}
SPAM <- .jnew("ca/pfv/spmf/algorithms/sequentialpatterns/spam/AlgoSPAM")
```

```{r}
print(SPAM)
.jconstructors(SPAM)
.jmethods(SPAM)
```

```{r}
#inputFile <- read.delim("/Users/solonioannou/IdeaProjects/SPMF_Algorithms/src/ca/pfv/spmf/test/contextPrefixSpan.txt", header = FALSE)
#outputFile <- "/Users/solonioannou/Temp/SPMFoutput/output_spamfromR_test1.txt"

# As a summary, the runAlgorithm() function takes as inputs:
# 1) location of the inputfile where the sequences are present
# 2) location where the file should be saved
# 3) scalar indicating support to be used

inspectinputfile <-read.delim("/Users/solonioannou/IdeaProjects/SPMF_Algorithms/src/ca/pfv/spmf/test/contextPrefixSpan.txt", header = FALSE)
inputFile <- "/Users/solonioannou/IdeaProjects/SPMF_Algorithms/src/ca/pfv/spmf/test/contextPrefixSpan.txt"
outputFile <- "/Users/solonioannou/Temp/SPMFoutput/output_spamfromR_test1.txt"
support = 0.2

command = paste("java ")

.jcall(SPAM, returnSig = "V", method = "runAlgorithm", inputFile, outputFile, support)
```

Hoorayyyy!!!!!! trible double bam!!

```{r}
.DollarNames(SPAM)

.jcall(SPAM, method = "printStatistics")
```

Adding AlgoSPAM to a function

Adding prefixSpan

```{r}
prefixspan <- .jnew("ca/pfv/spmf/algorithms/sequentialpatterns/prefixspan/AlgoPrefixSpan")
.jconstructors(prefixspan)
.jmethods(prefixspan)
.DollarNames(prefixspan)

outputFile <- "/Users/solonioannou/Temp/SPMFoutput/output_prefixspanfromR.txt"
support = 0.2

.jcall(prefixspan, returnSig = "[V", method = "runAlgorithm", inputFile, outputFile, support, 5L)
```

Adding Spade

```{r}

SPADE <- .jnew("ca/pfv/spmf/algorithms/sequentialpatterns/spade_spam_AGP/AlgoSPADE")

```

Command line executable 

```{r}

```

