---
title: "Creating a cohort of MI patients"
author: "Solon Ioannou"
date: "7/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Loading libraries
library(tidyverse)
library(arules)
library(arulesSequences)
library(Eunomia)
#Set up connection details
connectionDetails <- getEunomiaConnectionDetails()
connection <- connect(connectionDetails)
```

```{r, include=FALSE}
pat_obs <- querySql(connection, "SELECT COUNT(*) FROM person;")
cond_obs <- querySql(connection, "SELECT COUNT(*) FROM condition_occurrence;")
vis_obs <- querySql(connection, "SELECT COUNT(*) FROM visit_occurrence;")

querySql(connection, "SELECT count(*) FROM condition_occurrence WHERE condition_concept_id = 4329847;")
querySql(connection, "SELECT * FROM condition_occurrence WHERE condition_concept_id = 4329847;")

```

```{r, include=FALSE}
df <- querySql(connection, "
SELECT cond.PERSON_ID AS ID, CONDITION_CONCEPT_ID, CONDITION_SOURCE_VALUE, cond.VISIT_OCCURRENCE_ID, cond.CONDITION_START_DATE, conc.CONCEPT_NAME  
FROM condition_occurrence AS cond INNER JOIN CONCEPT AS conc ON CONDITION_CONCEPT_ID = CONCEPT_ID; ")

df_drugs <- querySql(connection, "
SELECT drug.PERSON_ID AS ID, DRUG_CONCEPT_ID, drug.VISIT_OCCURRENCE_ID, conc.CONCEPT_NAME  
FROM drug_exposure AS drug INNER JOIN CONCEPT AS conc ON DRUG_CONCEPT_ID = CONCEPT_ID; ")
```


```{r, include=FALSE}
disconnect(connection)
```

```{r}
df %>% summarise(mi = sum(CONDITION_CONCEPT_ID== 4329847))
#Which patients have MI
patientid <- df %>% filter(CONDITION_CONCEPT_ID== 4329847) %>% select(ID)

df_all<- inner_join(df, df_drugs, by = ID)

#Select all patients with MI
df_mi <- df %>% group_by(ID) %>% filter(ID %in% patientid$ID) %>% ungroup() %>% arrange(ID, CONDITION_START_DATE) 
length(unique(df_mi$ID))
nrow(df_mi)
#Select first data up to the first occurrence
df_mi <-df_mi %>% group_by(ID) %>% filter(cumsum(cumsum(CONDITION_CONCEPT_ID == 4329847)) <= 1L) %>% ungroup()
nrow(df_mi)
```

```{r}
df_midrugs <- df_drugs %>% group_by(ID) %>% filter(ID %in% patientid$ID) %>% ungroup() %>% arrange(ID) 

df_nomidrugs <- df_drugs %>% group_by(ID) %>% filter(ID %notin% patientid$ID) %>% ungroup() %>% arrange(ID)


df_midrugs_input <- select(df_midrugs, c(ID, CONCEPT_NAME))
df_nomidrugs_input <- select(df_nomidrugs, c(ID, CONCEPT_NAME))

df_midrugs_input <- as.data.frame(df_midrugs_input)
df_nomidrugs_input <- as.data.frame(df_nomidrugs_input)
trans_sets_midrugs <- as(split(df_midrugs_input[,"CONCEPT_NAME"], df_midrugs_input[,"ID"]), "transactions")
trans_sets_nomidrugs <- as(split(df_nomidrugs_input[,"CONCEPT_NAME"], df_nomidrugs_input[,"ID"]), "transactions")

```

# For association rules

```{r}
`%notin%` <- Negate(`%in%`)
#Select all patients without Mi
patientid <- df %>% filter(CONDITION_CONCEPT_ID == 14329847) %>% select(ID)
#Select all patients with MI
df_nomi <- df %>% group_by(ID) %>% filter(ID %notin% patientid$ID) %>% ungroup() %>% arrange(ID, CONDITION_START_DATE)
 
# Prepare datasets for apriori. 
df_nomi_apr <- df_nomi %>% select(ID, CONDITION_CONCEPT_ID, VISIT_OCCURRENCE_ID, CONCEPT_NAME) 
df_mi_apr <- df_mi %>% select(ID, CONDITION_CONCEPT_ID, VISIT_OCCURRENCE_ID, CONCEPT_NAME)

df_mi_input <- select(df_mi_apr, c(ID, CONCEPT_NAME))
df_nomi_input <- select(df_nomi_apr, c(ID, CONCEPT_NAME))
class(df_mi_input)
df_mi_input <- as.data.frame(df_mi_input)
df_nomi_input <- as.data.frame(df_nomi_input)
trans_sets_mi <- as(split(df_mi_input[,"CONCEPT_NAME"], df_mi_input[,"ID"]), "transactions")
trans_sets_nomi <- as(split(df_nomi_input[,"CONCEPT_NAME"], df_nomi_input[,"ID"]), "transactions")
```

```{r}
cols <- c("ID", "CONDITION_CONCEPT_ID", "VISIT_OCCURRENCE_ID", "CONCEPT_NAME")
df_nomi_apr[, cols] <- lapply(df_nomi_apr[, cols], factor)
df_mi_apr[, cols] <- lapply(df_mi_apr[, cols], factor)
```



# For Pattern sequence

```{r}
#convert relevant variable to factor
cols <- c("ID", "CONDITION_CONCEPT_ID", "VISIT_OCCURRENCE_ID", "CONCEPT_NAME")
df_mi[, cols] <- lapply(df_mi[, cols], factor)
str(df_mi)
summary(df_mi)
```

```{r}
df_mi <- df_mi %>% group_by(ID) %>% arrange(ID, CONDITION_START_DATE)
df_mi_input <- select(df_mi, c(ID, CONCEPT_NAME))

#How many conditions per person in the dataset?
df_mi %>% 
  group_by(ID) %>%
  summarise(no_rows = length(ID))

#Average conditions per person in the dataset?
a <- df_mi %>% 
  group_by(ID) %>%
  summarise(no_rows = length(ID))
mean(a$no_rows)

# Confirming distinct values in the ID variable
length(unique(df_mi$ID))

df_mi %>% 
  group_by(ID) %>%
  summarise(no_rows = length(ID)) %>% 
  ggplot(aes(no_rows)) + geom_density()

df_mi %>% 
  group_by(ID) %>%
  summarise(no_rows = length(ID)) %>% 
  ggplot(aes(no_rows)) + geom_histogram()
```

```{r}
# Preparing dataset without temporal information
df_mi_input <- as.data.frame(df_mi_input)
class(df_mi_input)
trans_sets <- as(split(df_mi_input[,"CONCEPT_NAME"], df_mi_input[,"ID"]), "transactions")
# Note that here an error is thrown:"removing duplicated items in transactions". Consequence of not considering time components and possibility of repeated events/diagnoses

#For larger datasets, consider a variation of the below for scaling.
#df_test2 <- df_mi %>%
#  select(ID, CONCEPT_NAME) %>%
#  distinct() %>%
#  mutate(value = 1) %>%
#  pivot_wider(CONCEPT_NAME, value, fill = 0)

#itemMatrix <- as(as.matrix(df_mi[, -1]), 'transactions')

# To inspect the resulting input dataset
#inspect(trans_sets)
#Get the input matrix
#trans_sets@data
```

```{r}
# Preparing dataset with temporal information
trans_sequence <- df_mi %>%
  group_by(ID, CONDITION_START_DATE) %>%
  summarize(
    SIZE = n(),
    CONCEPT = paste(as.character(CONCEPT_NAME), collapse = ';')
  )

trans_sequence$eventID <-  sequence(rle(as.character(trans_sequence$ID))$lengths)

trans_sequence <- select(trans_sequence, c(ID, eventID, SIZE, CONCEPT ))
names(trans_sequence) <- c("sequenceID", "eventID", "SIZE", "items")
trans_sequence <- data.frame(lapply(trans_sequence, as.factor))
trans_sequence <- trans_sequence[order(trans_sequence$sequenceID, trans_sequence$eventID),]


#elapsed_months <- function(end_date, start_date) {
#  ed <- as.POSIXlt(end_date)
#  sd <- as.POSIXlt(start_date)
#  12 * (ed$year - sd$year) + (ed$mon - sd$mon)
#}

#write.table(trans_sequence, "mytxtout.txt", sep=";", row.names = FALSE, col.names = FALSE, quote = FALSE)
#trans_matrix <- read_baskets("mytxtout.txt", sep = ";", info = c("sequenceID","eventID","SIZE"))

```

```{r}
#saveRDS(df, file = "../data/processed/eunomia_man.rds")
saveRDS(trans_sets_mi, file = "../processed/eunomia_MI_trans_sets.rds")
saveRDS(trans_sets_nomi, file = "../processed/eunomia_NO_MI_trans_sets.rds")

saveRDS(trans_sets_midrugs, file = "../processed/eunomia_MI_trans_sets_DRUGS.rds")
saveRDS(trans_sets_nomidrugs, file = "../processed/eunomia_NO_MI_trans_sets_DRUGS.rds")


write.table(trans_sequence, "../processed/eunomia_MI_trans_seqs.txt", sep=";", row.names = FALSE, col.names = FALSE, quote = FALSE)
```