---
title: "Untitled"
author: "Solon Ioannou"
date: "7/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(FeatureExtraction)
library(SqlRender)
library(Eunomia)
connectionDetails <- getEunomiaConnectionDetails()
connection <- connect(connectionDetails)
```

# Load data

```{r}
sql <- readSql("../data/cohorts/heart_failure_2.sql")
sql <- render(sql,
vocabulary_database_schema = "vocabulary",   
cdm_database_schema = "cdm_schema",
target_database_schema = "scratch", 
target_cohort_table = "new", 
target_cohort_id = 1)
sql <- translate(sql, targetDialect = connectionDetails$dbms)
#connection <- connect(connectionDetails)
executeSql(connection, sql)
```

```{r}
querySql(connection, "SELECT * FROM concept WHERE concept_id = '316139';")
querySql(connection, "SELECT * FROM condition_occurrence WHERE concept_id = '24329847';")
querySql(connection, "SELECT * FROM concept WHERE concept_name = 'Heart failure';")
querySql(connection, "SELECT COUNT(*) AS count
FROM cdm_synthea.new;")
querySql(connection, "SELECT count(*) FROM condition_occurrence WHERE condition_concept_id= '316139' ;")
```


```{r, include=FALSE}
disconnect(connection)
```

# Create Covariates

```{r}
covariateSettings <- createDefaultCovariateSettings()
```

