---
title: "Preparing dataset"
author: "Solon Ioannou"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(arules)
library(arulesSequences)
```

```{r}
#import data
df <- readRDS("../data/raw/df.rds")
str(df)
```

```{r}
#convert relevant variable to factor
cols <- c("ID", "CONDITION_CONCEPT_ID", "VISIT_OCCURRENCE_ID", "CONCEPT_NAME")
df[, cols] <- lapply(df[, cols], factor)
str(df)
summary(df)
```

```{r}
df <- df %>% group_by(ID) %>% arrange(ID, CONDITION_START_DATE)
df_input <- select(df, c(ID, CONCEPT_NAME))

#How many conditions per person in the dataset?
df %>% 
  group_by(ID) %>%
  summarise(no_rows = length(ID))

#Average conditions per person in the dataset?
a <- df %>% 
  group_by(ID) %>%
  summarise(no_rows = length(ID))
mean(a$no_rows)

# Confirming distinct values in the ID variable
length(unique(df$ID))

df %>% 
  group_by(ID) %>%
  summarise(no_rows = length(ID)) %>% 
  ggplot(aes(no_rows)) + geom_density()

df %>% 
  group_by(ID) %>%
  summarise(no_rows = length(ID)) %>% 
  ggplot(aes(no_rows)) + geom_histogram()
```

```{r}
# The following is a conversion of the data from the long format in it's wide format representation.
df_test <- df %>% 
  mutate(value = 1) %>% 
  pivot_wider(id_cols = ID, names_from = CONCEPT_NAME, values_from = value)
head(df_test)
# From the resulting dataframe, it is obvious that the temporal character is obvious in this format as the time component is not preserved.  

```

```{r}
# Preparing dataset without temporal information
df_input <- as.data.frame(df_input)
class(df_input)
trans_sets <- as(split(df_input[,"CONCEPT_NAME"], df_input[,"ID"]), "transactions")
# Note that here an error is thrown:"removing duplicated items in transactions". Consequence of not considering time components and possibility of repeated events/diagnoses

#For larger datasets, consider a variation of the below for scaling.
#df_test2 <- df %>%
#  select(ID, CONCEPT_NAME) %>%
#  distinct() %>%
#  mutate(value = 1) %>%
#  pivot_wider(CONCEPT_NAME, value, fill = 0)

#itemMatrix <- as(as.matrix(df[, -1]), 'transactions')

# To inspect the resulting input dataset
#inspect(trans_sets)
#Get the input matrix
#trans_sets@data
```

```{r}
# Preparing dataset with temporal information
trans_sequence <- df %>%
  group_by(ID, CONDITION_START_DATE) %>%
  summarize(
    SIZE = n(),
    CONCEPT = paste(as.character(CONCEPT_NAME), collapse = ';')
  )

trans_sequence$eventID <-  sequence(rle(as.character(trans_sequence$ID))$lengths)

trans_sequence <- select(trans_sequence, c(ID, eventID, SIZE, CONCEPT ))
names(trans_sequence) <- c("sequenceID", "eventID", "SIZE", "items")
trans_sequence <- data.frame(lapply(trans_sequence, as.factor))
trans_sequence <- trans_sequence[order(trans_sequence$sequenceID, trans_sequence$eventID),]


#elapsed_months <- function(end_date, start_date) {
#  ed <- as.POSIXlt(end_date)
#  sd <- as.POSIXlt(start_date)
#  12 * (ed$year - sd$year) + (ed$mon - sd$mon)
#}

#write.table(trans_sequence, "mytxtout.txt", sep=";", row.names = FALSE, col.names = FALSE, quote = FALSE)
#trans_matrix <- read_baskets("mytxtout.txt", sep = ";", info = c("sequenceID","eventID","SIZE"))

```
```{r}
data.frame(trans@itemsetInfo)
```


```{r}
saveRDS(df, file = "../data/processed/eunomia_man.rds")
saveRDS(trans_sets, file = "../data/processed/eunomia_trans_sets.rds")
write.table(trans_sequence, "../data/processed/eunomia_trans_seqs.txt", sep=";", row.names = FALSE, col.names = FALSE, quote = FALSE)
```



