---
title: "Untitled"
author: "Solon Ioannou"
date: "7/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(arules)
library(arulesViz)
library(rCBA)
library(tidyverse)
```

```{r}
mi <- readRDS("../data/processed/eunomia_MI_trans_sets_DRUGS.rds")
nomi <- readRDS("../data/processed/eunomia_NO_MI_trans_sets_DRUGS.rds")
#data2 <- readRDS("../data/processed/synthea60k_trans.rds")
```

```{r}
itemfreq1 <- itemFrequency(mi) #gives support fr each item
itemfreq2 <- itemFrequency(nomi)
sort(itemfreq1, decreasing = TRUE)
sort(itemfreq2, decreasing = T)
#itemfreq2 <- itemFrequency(data2) #gives support fr each item
#sort(itemfreq2, decreasing = TRUE)
itemFrequencyPlot(data1, support = 0, cex.names = 0.5)
#itemFrequencyPlot(data2, support = 0.01, cex.names = 0.8)
```

```{r}
#Define parameters for apriori algorithm. See ?APparameter for more details
ap_params <- list(
  support = 0.5, 
  confidence = 0.5, 
  minlen = 1,     #number of items per itemset
  maxlen = 50,    #maximal number of items per itemset 
  arem = "chi2",  #additional rule evaluation
  aval = TRUE,    #return additional rule measure
  minval = 0,   #default value for minimal value of additional rule measure
  maxtime = 0,     #Disabling he limit for subset checking
  target = "closed frequent itemsets"
)

```


```{r}
rules1 <- apriori(mi, parameter = ap_params)
rules2 <- apriori(nomi, parameter = ap_params)
#rules1
summary(rules1)
summary(rules2)
#rules_insp1 <- inspect(rules1)
rules_conf1 <- sort(rules1, by="confidence", decreasing=TRUE) # 'high-confidence' rules.
rules_conf2 <- sort(rules2, by="confidence", decreasing = TRUE)
#inspect(rules_conf1)
inspect(head(rules_conf1))
inspect(tail(rules_conf1))


inspect(rules_conf2)
inspect(head(rules_conf2))
inspect(tail(rules_conf2))

rules_chisqu1 <- sort(rules1, by="chi2", decreasing=TRUE) # 'high-confidence' rules.
inspect(rules_chisqu1)
```

```{r}
ind_rules1 <- ruleInduction(rules1, mi, control = list(verbose =TRUE) ) 
ind_rules2 <- ruleInduction(rules2, nomi, control = list(verbose = TRUE))

ind_rules1_lift <- sort(ind_rules1, by = "support")
ind_rules2_lift <- sort(ind_rules2, by = "support")
in_r1 <- head(ind_rules1_lift, 10)
in_r2 <- head(ind_rules2_lift, 10)

plot(in_r1, method = "graph")
plot(in_r1, method = "graph")

as.matrix(is.subset(in_r1, in_r2))

as(in_r1, "data.frame")

in_r1@rhs@itemInfo

as(in_r1, "data.frame")
as(in_r2, "data.frame")
```


```{r}
plot(rules1)
```

```{r}
plot(rules1, method = "graph",  engine = "htmlwidget")
```

```{r}
drugs_midf <- as(in_r1, "data.frame")

drugs_midf$rulecount <- as.character(drugs_midf$rule)
max_col <- max(sapply(strsplit(drugs_midf$rulecount,' => '),length))
r_sep <- separate(data = drugs_midf, col = rules, into = paste0("Time",1:max_col), sep = " =>")
#remove brackets
r_sep$Time2 <- substring(r_sep$Time2,3,nchar(r_sep$Time2)-2)

# Strip LHS baskets
max_time1 <- max(sapply(strsplit(r_sep$Time1,','),length))
r_sep$TimeClean <- substring(r_sep$Time1,2,nchar(r_sep$Time1)-2)
r_sep$TimeClean <- gsub("\\},\\{", "=>", r_sep$TimeClean)
r_sep_items <- separate(data = r_sep, col = TimeClean, into = paste0("Previous_Items",1:max_time1), sep = " =>")
#r_sep <- separate(data = r_sep, col = TimeClean, into = paste0("Previous_items",1:max_time1), sep = " => ")

#unlist(strsplit(finalseq_df$rule, "[]"))

#r_sep
```



```{r}
nodes_mi<- data.frame(drugs = c(r_sep_items$Time1, r_sep_items$Time2 ))
unique(nodes_mi$drugs)

```



