---
title: "Untitled"
author: "Solon Ioannou"
date: "7/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(arules)
library(arulesViz)
library(rCBA)
library(tidyverse)
```

```{r}
data1 <- readRDS("../data/processed/eunomia_MI_trans_sets.rds")
#data2 <- readRDS("../data/processed/synthea60k_trans.rds")
```

```{r}
itemfreq1 <- itemFrequency(data1) #gives support fr each item
sort(itemfreq1, decreasing = TRUE)

#itemfreq2 <- itemFrequency(data2) #gives support fr each item
#sort(itemfreq2, decreasing = TRUE)
itemFrequencyPlot(data1, support = 0, cex.names = 0.5)
#itemFrequencyPlot(data2, support = 0.01, cex.names = 0.8)
```

```{r}
#Define parameters for apriori algorithm. See ?APparameter for more details
ap_params <- list(
  support = 0.5, 
  confidence = 0.5, 
  minlen = 1,     #number of items per itemset
  maxlen = 50,    #maximal number of items per itemset 
  arem = "chi2",  #additional rule evaluation
  aval = TRUE,    #return additional rule measure
  minval = 0,   #default value for minimal value of additional rule measure
  maxtime = 0     #Disabling he limit for subset checking
)

```


```{r}
rules1 <- apriori(data1, parameter = list(support = 0.5, confidence = 0.5))
rules1 <- apriori(data1, parameter = ap_params)
rules1
summary(rules1)
rules_insp1 <- inspect(rules1)
rules_conf1 <- sort(rules1, by="confidence", decreasing=TRUE) # 'high-confidence' rules.
inspect(rules_conf1)
inspect(head(rules_conf1))
inspect(tail(rules_conf1))

rules_chisqu1 <- sort(rules1, by="chi2", decreasing=TRUE) # 'high-confidence' rules.
inspect(rules_chisqu1)
```

```{r}
plot(rules1)
```

```{r}
plot(rules1, method = "graph",  engine = "htmlwidget")
```

```{r}
#library(arules); 
search() 
unloadNamespace(c("rCBA", "arules", "arulesSequences")) 
update.packages("arules")
update.packages("arulesSequences")
library(arules)
```

